### ISSUE TITLE
Add new Roblox icons

### ISSUE THREAD

**Issue by alexop1000** [DervexHero/Argon#11]
Awesome extension/plugin!

I think that if you could add support for the new Roblox studio icons in VSCode, that would be really awesome. I prefer them much over the old ones.

**Comment by AridDev** [comment]
I don't think he'll add this feature as you can do this manually.

- Go over to
```
%USERPROFILE%\.vscode\extensions\
```
- Find `dervex.argon-{current_version}`
- Go to assets\icons
- Replace the icons there with your icons.

**Comment by alexop1000** [comment]
Why not just implement them for everyone, though? I know that many people prefer it. Or at least make it a toggle for those who prefer the new icons.

**Comment by AridDev** [comment]
I think he once said that he won't be adding that system. (Pretty sure, I was the one who requested it. I'll try and find it)

**Comment by alexop1000** [comment]
Maybe. But having the icons match the default studio ones makes more sense. I could send a pull request updating the icons if I get time.
