### ISSUE TITLE
Argon fails to connect after recent vsc update

### ISSUE THREAD

**Issue by TheFortex** [DervexHero/Argon#12]
When I launch VS Code I immediately get this notification from Argon
![image](https://github.com/DervexHero/Argon/assets/60301549/bc703a16-fd24-4c59-afd1-e99aa6b3c45f)
and the studio plugin is just stuck saying "connecting" and nothing is syncing from either side
![image](https://github.com/DervexHero/Argon/assets/60301549/bfd53eba-f222-4403-a9fd-34dbd3f0404d)
If I disable argon in VS Code the Roblox plugin correctly exits
![image](https://github.com/DervexHero/Argon/assets/60301549/5559f9de-05a8-4951-b5f9-1e8e4c0ad1f5)
but then when I turn it on again and try to reconnect it does the same thing where it hangs on "connecting"

**Comment by TheFortex** [comment]
I'm using the normal VS code not the insider's version for reference

**Comment by DervexHero** [comment]
Fixed in d9ee0945d6e47d3e25991d5e3b66ff34a3bb72d4,
