### ISSUE TITLE
Parenting a script to StarterCharacterScripts or StarterPlayerScripts does not show any code when importing to roblox

### ISSUE THREAD

**Issue by Loomiquu** [DervexHero/Argon#6]
![image](https://user-images.githubusercontent.com/107811831/208343245-d7b8dc1c-c202-4a7b-887d-32b553e88539.png)

![image](https://user-images.githubusercontent.com/107811831/208343276-13938eae-5035-4cf6-9538-95cab24e78a1.png)

**Comment by DervexHero** [comment]
Fixed in [0.5.3](https://github.com/DervexHero/Argon/commit/00be2930ddd165d80e361df6ced931089b9644bb). Thanks for reporting!
