### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by BloxFlipRblx** [DervexHero/Argon#7]
Command 'Argon: Open Menu' resulted in an error (command 'argon.openMenu' not found)

**Comment by DervexHero** [comment]
Could you provide some extra info? Because what you said doesn't help at all.

You might find some useful data inside Extensions > Argon > Runtime Status.

Also what OS are you using?

**Comment by BloxFlipRblx** [comment]
Mac OS

**Comment by BloxFlipRblx** [comment]
<img width="497" alt="image" src="https://user-images.githubusercontent.com/126255251/221602251-2d36cbfa-5ee3-46d6-a001-e1226edf2a63.png">
