### ISSUE TITLE
Argon Commands resulting in an error

### ISSUE THREAD

**Issue by Loomiquu** [DervexHero/Argon#9]
![image](https://user-images.githubusercontent.com/107811831/236116176-4b1ba913-c0ed-4068-94ca-47a6931d7d63.png)

![image](https://user-images.githubusercontent.com/107811831/236116543-4feb8cfe-81fb-4e29-a844-ea2e11ea8936.png)

The newest release version of Argon has been throwing this error, taking one glance at the DevForum's it seems to be a prominent issue. 

Reinstalling the plugin and reloading VSCode doesn't seem to fix it, either.

**Comment by DervexHero** [comment]
Good news! Finally found the issue. It’s related to the embedded C++ file which is only used on Windows to manipulate user’s input. It has something to do with node.js version mismatch, so I’m working on a fix!

**Comment by rotntake** [comment]
> Good news! Finally found the issue. It’s related to the embedded C++ file which is only used on Windows to manipulate user’s input. It has something to do with node.js version mismatch, so I’m working on a fix!

Is it possible if you could tell me what the correct version of node.js is?

**Comment by DervexHero** [comment]
Unfortunately you would have to downgrade VSC to make it work as it runs its own version of node.js. You can check that by clicking on Code > About Visual Studio Code (macOS)  or Help > About (Windows).

I compiled that C++ file with the latest Electron headers and it fixed the issue on my Windows PC. However before publishing the update I would like to make sure that it won't brake Argon for other users.

Could you try this by yourself? Here is the [file](https://drive.google.com/file/d/1CUsGOTP9aTccZZpsF6kn2uu02mlpMNmM/view?usp=sharing).

**Comment by rotntake** [comment]
Sure.

**Comment by rotntake** [comment]
It works perfectly! There aren't any issues with syncing code or such. Only warning/error I got was a version mismatch which didn't restrict me from doing anything at all.

**Comment by DervexHero** [comment]
Happy to hear that! Just released [1.2.3 update](https://github.com/DervexHero/Argon/releases/tag/1.2.3).
